# SPDX-FileCopyrightText: 2021 yuzu Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

name: Reuse

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]
jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: fsfe/reuse-action@v4
